language: objective-c
osx_image: xcode10.1

env:
    global:
        - WORKSPACE=Pace.xcworkspace
        - SCHEME=Pace
        - SDK=iphonesimulator12.1
        - DESTINATION="platform=iOS Simulator,OS=latest,name=iPhone 7"

script:
    - xcodebuild test -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -parallelizeTargets -enableCodeCoverage YES -quiet ONLY_ACTIVE_ARCH=YES
